# Auto-generated by service gen
from __future__ import annotations
import json as _json, os, re, shutil, threading
from pathlib import Path
from typing import Optional
from fastapi import APIRouter, File, HTTPException, UploadFile
from fastapi.responses import FileResponse
from service.config import settings
from service.schemas.models import CANVAS_FORMATS
from service.schemas.models import DesignChoice, GenerateRequest, OutlineGenerate
from service.schemas.models import OutlineUpdate, Project, ProjectCreate
from service.schemas.models import ProjectOutline, ProjectStatus
from service.schemas.models import SlideOutline, SourceEntry
from service.schemas.models import SourceUrlInput, StyleSelect, TaskStatus, TopicInput
from service.utils import scripts as s
from service.utils.tasks import create_task, load_task
from service.utils.tasks import set_task_result, set_task_error
from service.utils.tasks import update_step, update_task_status
from service.utils.llm import call_llm, try_parse_json

router = APIRouter()

def _pd(pid): return Path(settings.projects_dir) / pid
def _mp(pid): return _pd(pid) / '.ppt_service.json'

def load_project(pid):
    p = _mp(pid)
    if not p.exists(): return None
    try: return Project(**_json.loads(p.read_text('utf-8')))
    except: return None

def save_project(proj):
    proj.touch()
    p = _mp(proj.id); p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_json.dumps(proj.model_dump(), ensure_ascii=False, indent=2), 'utf-8')

def list_projects():
    result = []
    for p in Path(settings.projects_dir).iterdir():
        if p.is_dir():
            meta = p / '.ppt_service.json'
            if meta.exists():
                try: result.append(Project(**_json.loads(meta.read_text('utf-8'))))
                except: pass
    result.sort(key=lambda x: x.updated_at, reverse=True)
    return result

def _gpo404(pid):
    proj = load_project(pid)
    if not proj: raise HTTPException(404, f'Project {pid} not found')
    return proj

def _gst(proj):
    parts = []
    if proj.topic: parts.append('## Topic\\n' + proj.topic)
    for src in proj.sources:
        if src.converted and src.converted_path:
            fp = _pd(proj.id) / src.converted_path
            if fp.exists(): parts.append('## ' + src.original_name + '\\n' + fp.read_text(encoding='utf-8'))
    return '\\n\\n---\\n\\n'.join(parts)

import re


def _sanitize_id(name):
    safe = re.sub(r"[^\w\-]", "_", name).strip("_") or "project"
    return safe


@router.post("/api/projects")
def create_project(body: ProjectCreate):
    if load_project(body.name): raise HTTPException(400, "Already exists")
    safe_id = _sanitize_id(body.name)
    proj = Project(id=safe_id, name=body.name, format=body.format, status=ProjectStatus.created)
    proj.touch()
    ok, r = s.project_init(safe_id, body.format)
    if not ok: raise HTTPException(500, f"Init failed: {r}")
    result_path = Path(r)
    if not result_path.is_absolute():
        result_path = Path(settings.ppt_master_dir) / result_path
    if result_path.exists():
        proj.id = result_path.name
    save_project(proj)
    return proj

@router.get("/api/projects")
def get_projects(): return list_projects()

@router.get("/api/projects/{project_id}")
def get_project(project_id: str): return _gpo404(project_id)

@router.delete("/api/projects/{project_id}")
def delete_project(project_id: str):
    _gpo404(project_id)
    d = _pd(project_id)
    if d.exists(): shutil.rmtree(d)
    return {"ok": True}

# Sources
@router.post("/api/projects/{project_id}/sources")
async def upload_sources(project_id: str, files: list[UploadFile] = File(...)):
    proj = _gpo404(project_id)
    sd = _pd(project_id) / "sources"; sd.mkdir(parents=True, exist_ok=True)
    for f in files:
        fp = sd / (f.filename or "u")
        fp.write_bytes(await f.read())
        entry = SourceEntry(filename=f.filename or "u", original_name=f.filename or "u", file_type=fp.suffix.lower())
        ok, _ = s.convert_file(str(fp))
        if ok:
            entry.converted = True
            for x in sd.iterdir():
                if x.suffix == ".md" and x.stem == fp.stem: entry.converted_path = "sources/" + x.name; break
        proj.sources.append(entry)
    if proj.status == ProjectStatus.created: proj.status = ProjectStatus.sourcing
    save_project(proj)
    return {"ok": True, "sources": proj.sources}

@router.post("/api/projects/{project_id}/sources/url")
def import_url(project_id: str, body: SourceUrlInput):
    proj = _gpo404(project_id)
    ok, r = s.convert_url(body.url)
    if not ok: raise HTTPException(500, f"URL fail: {r}")
    proj.sources.append(SourceEntry(filename=body.url, original_name=body.url, converted=True, file_type="url"))
    if proj.status == ProjectStatus.created: proj.status = ProjectStatus.sourcing
    save_project(proj)
    return {"ok": True, "sources": proj.sources}

@router.put("/api/projects/{project_id}/topic")
def set_topic(project_id: str, body: TopicInput):
    proj = _gpo404(project_id)
    proj.topic = body.topic
    if proj.status in (ProjectStatus.created, ProjectStatus.sourcing): proj.status = ProjectStatus.sourcing
    save_project(proj)
    return {"ok": True, "topic": proj.topic}

@router.get("/api/projects/{project_id}/sources")
def get_sources(project_id: str):
    proj = _gpo404(project_id)
    sd = _pd(project_id) / "sources"
    fl = sorted([{"name": f.name, "size": f.stat().st_size, "type": f.suffix} for f in sd.iterdir()]) if sd.exists() else []
    return {"sources": proj.sources, "files": fl}

# Outline
OUTLINE_PROMPT = """You are a PPT strategist. Generate JSON slide outline.
Output: [{"id": 1, "title": "...", "content": "...", "layout": "cover|content-text|content-image|comparison|chart|timeline|list|ending", "notes": "..."}]
First: cover, last: ending. 8-15 slides. Concise titles."""

@router.post("/api/projects/{project_id}/outline")
def generate_outline(project_id: str, body: Optional[OutlineGenerate] = None):
    proj = _gpo404(project_id)
    src = _gst(proj)
    if not src.strip(): raise HTTPException(400, "No source content")
    b = body or OutlineGenerate()
    ok, r = call_llm(OUTLINE_PROMPT, src)
    if not ok: raise HTTPException(500, f"LLM fail: {r}")
    sd = try_parse_json(r)
    if not sd or not isinstance(sd, list):
        raise HTTPException(500, f"No JSON array found in LLM response. Response: {r[:500]}")
    # Ensure each slide has an id field
    for i, s in enumerate(sd):
        if 'id' not in s:
            s['id'] = i + 1
    slides = [SlideOutline(**s) for s in sd]
    proj.outline = ProjectOutline(slides=slides, confirmed=False)
    proj.status = ProjectStatus.outlining
    save_project(proj)
    return proj.outline

@router.get("/api/projects/{project_id}/outline")
def get_outline(project_id: str): return _gpo404(project_id).outline

@router.put("/api/projects/{project_id}/outline")
def update_outline(project_id: str, body: OutlineUpdate):
    proj = _gpo404(project_id)
    proj.outline = ProjectOutline(slides=body.slides, confirmed=body.confirmed)
    if body.confirmed: proj.status = ProjectStatus.styling
    save_project(proj)
    return proj.outline

# Style
@router.post("/api/projects/{project_id}/style")
def select_style(project_id: str, body: StyleSelect):
    proj = _gpo404(project_id)
    proj.design = DesignChoice(style_id=body.style_id, mode_id=body.mode_id,
        colors=body.colors or proj.design.colors, fonts=body.fonts or proj.design.fonts, confirmed=True)
    proj.status = ProjectStatus.ready
    save_project(proj)
    return proj.design

@router.get("/api/projects/{project_id}/design-preview")
def design_preview(project_id: str):
    proj = _gpo404(project_id)
    return {"format": proj.format, "page_count": len(proj.outline.slides),
        "style_id": proj.design.style_id, "colors": proj.design.colors.model_dump(),
        "fonts": proj.design.fonts.model_dump(), "confirmed": proj.outline.confirmed and proj.design.confirmed}

# Generation pipeline helpers
def _gen_design_spec(proj, pd_):
    c = proj.design.colors; f_ = proj.design.fonts
    sj = _json.dumps([s.model_dump() for s in proj.outline.slides], ensure_ascii=False, indent=2)
    sp = "You are PPT Strategist. Make design_spec.md.\nStyle: " + proj.design.style_id + "\nColors: primary=" + c.primary + "\nFonts: heading=" + f_.heading + "\nOutline:\n" + sj
    ok, r = call_llm(sp, "Generate.")
    if not ok: return False, r
    (pd_ / "design_spec.md").write_text(r, "utf-8")
    (pd_ / "spec_lock.md").write_text(r, "utf-8")
    return True, r

def _gen_svg(proj, slide, pd_):
    c = proj.design.colors; f_ = proj.design.fonts
    sp = ("You are PPT Executor. SVG slide.\n" + str(slide.id) + ": " + slide.title +
        "\nLayout: " + slide.layout + "\nContent: " + slide.content +
        "\nColors: primary=" + c.primary + " bg=" + c.background +
        "\nFonts: " + f_.heading + "\n1920x1080\nOutput ONLY SVG.")
    ok, r = call_llm(sp, "Gen page " + str(slide.id), max_tokens=8192)
    if not ok: return False, r
    m = re.search(r"<svg[\s\S]*?</svg>", r, re.IGNORECASE)
    svgc = m.group() if m else r
    # Fix unescaped & in XML (e.g. Google Fonts URLs)
    svgc = re.sub(r'&(?!amp;|lt;|gt;|quot;|apos;|#\d+;|#x[\da-fA-F]+;)', '&amp;', svgc)
    sd = pd_ / "svg_output"; sd.mkdir(parents=True, exist_ok=True)
    (sd / ("page_%02d.svg" % slide.id)).write_text(svgc, "utf-8")
    return True, "page_%02d.svg" % slide.id

def _gen_notes(proj, pd_):
    nd = pd_ / "notes"; nd.mkdir(parents=True, exist_ok=True)
    lines = ["## Page %d: %s\n%s" % (s.id, s.title, s.notes or s.content) for s in proj.outline.slides]
    (nd / "total.md").write_text("\n\n".join(lines), "utf-8")

# Pipeline runner
def _run_pipeline(pid, tid):
    task = load_task(tid)
    if not task: return
    pdir = _pd(pid); proj = load_project(pid)
    if not proj: set_task_error(task, "No project"); return
    try:
        update_task_status(task, "running", 0.05, "Design spec")
        update_step(task, 0, "running", "Design spec...")
        ok, r = _gen_design_spec(proj, pdir)
        if not ok: set_task_error(task, "Design: " + r); return
        update_step(task, 0, "completed", "Design spec done")

        slides = proj.outline.slides; total = len(slides)
        if total == 0: set_task_error(task, "No slides"); return
        update_step(task, 1, "running", "1/" + str(total))
        for i, sl in enumerate(slides):
            p = 0.1 + 0.7 * ((i + 1) / total)
            update_task_status(task, "running", p, "SVG " + str(i + 1) + "/" + str(total))
            update_step(task, 1, "running", str(i + 1) + "/" + str(total))
            ok2, r2 = _gen_svg(proj, sl, pdir)
            if not ok2:
                t = load_task(tid)
                if t: t.steps[1].detail += " | P" + str(i + 1) + " fail: " + r2[:80]
        update_step(task, 1, "completed", str(total) + " SVGs done")

        update_task_status(task, "running", 0.85, "Notes")
        update_step(task, 2, "running", "Notes...")
        _gen_notes(proj, pdir)
        update_step(task, 2, "completed", "Notes done")

        update_task_status(task, "running", 0.9, "Exporting...")
        update_step(task, 3, "running", "Export...")
        s.run_total_md_split(str(pdir))
        s.run_finalize_svg(str(pdir))
        ok3, r3 = s.run_svg_to_pptx(str(pdir))
        update_step(task, 3, "completed" if ok3 else "failed", r3[:200] if r3 else "")

        ex = pdir / "exports"
        ppts = sorted(ex.glob("*.pptx")) if ex.exists() else []
        if ppts:
            proj.status = ProjectStatus.done
            proj.task_id = None
            save_project(proj)
            set_task_result(task, {"export_path": "api/projects/" + pid + "/exports/" + ppts[-1].name})
        elif ok3:
            proj.status = ProjectStatus.done
            proj.task_id = None
            save_project(proj)
            set_task_result(task, {"message": "Export done"})
        else:
            proj.status = ProjectStatus.failed
            proj.task_id = None
            save_project(proj)
            set_task_error(task, "Export failed")
    except Exception as e:
        proj.status = ProjectStatus.failed
        proj.task_id = None
        save_project(proj)
        t = load_task(tid)
        if t: set_task_error(t, str(e))

# Generate trigger
@router.post("/api/projects/{project_id}/generate")
def submit_generation(project_id: str, body: Optional[GenerateRequest] = None):
    proj = _gpo404(project_id)
    if proj.status == ProjectStatus.generating: raise HTTPException(400, "Already generating")
    b = body or GenerateRequest()
    task = create_task(project_id=project_id, steps=["Design", "SVG", "Notes", "Export"])
    proj.status = ProjectStatus.generating
    proj.task_id = task.task_id
    save_project(proj)
    t = threading.Thread(target=_run_pipeline, args=(project_id, task.task_id), daemon=True)
    t.start()
    return {"task_id": task.task_id, "status": "running"}

# Exports
@router.get("/api/projects/{project_id}/exports")
def list_exports(project_id: str):
    _gpo404(project_id)
    d = _pd(project_id) / "exports"
    fl = [{"name": f.name, "size": f.stat().st_size} for f in sorted(d.glob("*.pptx"), reverse=True)] if d.exists() else []
    return {"exports": fl}

@router.get("/api/projects/{project_id}/exports/{fn:path}")
def download_export(project_id: str, fn: str):
    _gpo404(project_id)
    fp = _pd(project_id) / "exports" / fn
    if not fp.exists(): raise HTTPException(404, "Not found")
    return FileResponse(str(fp), media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", filename=fn)

# SVG management
@router.post("/api/projects/{project_id}/svg")
async def upload_svg(project_id: str, files: list[UploadFile] = File(...)):
    _gpo404(project_id)
    sd = _pd(project_id) / "svg_output"; sd.mkdir(parents=True, exist_ok=True)
    ul = []
    for f in files:
        if not f.filename or not f.filename.endswith(".svg"): continue
        (sd / f.filename).write_bytes(await f.read()); ul.append(f.filename)
    return {"ok": True, "uploaded": ul}

@router.get("/api/projects/{project_id}/svg")
def list_svg(project_id: str):
    d = _pd(project_id) / "svg_output"
    fl = [{"name": f.name, "size": f.stat().st_size} for f in sorted(d.glob("*.svg"))] if d.exists() else []
    return {"svg_files": fl}

@router.get("/api/projects/{project_id}/svg/{fn:path}")
def get_svg(project_id: str, fn: str):
    fp = _pd(project_id) / "svg_output" / fn
    if not fp.exists(): raise HTTPException(404, "Not found")
    return FileResponse(str(fp), media_type="image/svg+xml")

# Notes
@router.put("/api/projects/{project_id}/notes")
async def upload_notes(project_id: str, body: TopicInput):
    _gpo404(project_id)
    nd = _pd(project_id) / "notes"; nd.mkdir(parents=True, exist_ok=True)
    (nd / "total.md").write_text(body.topic, "utf-8")
    return {"ok": True}

@router.get("/api/projects/{project_id}/notes")
def get_notes(project_id: str):
    p = _pd(project_id) / "notes" / "total.md"
    return {"notes": p.read_text("utf-8") if p.exists() else ""}

# Tasks
@router.get("/api/tasks/{task_id}")
def get_task(task_id: str):
    task = load_task(task_id)
    if not task: raise HTTPException(404, "Not found")
    return task